==4325== Memcheck, a memory error detector
==4325== Copyright (C) 2002-2010, and GNU GPL'd, by Julian Seward et al.
==4325== Using Valgrind-3.6.1 and LibVEX; rerun with -h for copyright info
==4325== Command: python exampl.py
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525476: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==  Address 0x63c8020 is not stack'd, malloc'd or (recently) free'd
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x63c8020 is not stack'd, malloc'd or (recently) free'd
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x5254BD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x63c9020 is 176 bytes inside a block of size 400 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==  Address 0x6407020 is 304 bytes inside a block of size 464 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x46AEDC: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE568: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525476: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==  Address 0x6402020 is 48 bytes inside a block of size 368 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74C7: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==  Address 0x64e8020 is 8,608 bytes inside a block of size 10,120 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4FE5FC: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x5254BD: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==  Address 0x64e9020 is 208 bytes inside a block of size 464 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74C7: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==  Address 0x6507020 is not stack'd, malloc'd or (recently) free'd
==4325== 
==4325== Conditional jump or move depends on uninitialised value(s)
==4325==    at 0x47EA08: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325== 
==4325== Use of uninitialised value of size 8
==4325==    at 0x47EA22: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525579: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==  Address 0x639f020 is 976 bytes inside a block of size 1,608 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A7531: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x654d020 is 240 bytes inside a block of size 576 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Conditional jump or move depends on uninitialised value(s)
==4325==    at 0x47EC24: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x505FA8: _PyObject_GC_Resize (in /usr/bin/python2.7)
==4325==    by 0x4C6C37: PyFrame_New (in /usr/bin/python2.7)
==4325==    by 0x49975F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Use of uninitialised value of size 8
==4325==    at 0x47EC3E: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x505FA8: _PyObject_GC_Resize (in /usr/bin/python2.7)
==4325==    by 0x4C6C37: PyFrame_New (in /usr/bin/python2.7)
==4325==    by 0x49975F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47EC1B: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x505FA8: _PyObject_GC_Resize (in /usr/bin/python2.7)
==4325==    by 0x4C6C37: PyFrame_New (in /usr/bin/python2.7)
==4325==    by 0x49975F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==  Address 0x666d020 is 1,136 bytes inside a block of size 2,048 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x46AEDC: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C62E2: ??? (in /usr/bin/python2.7)
==4325==    by 0x499855: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47EC1B: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x482D1C: _PyString_Resize (in /usr/bin/python2.7)
==4325==    by 0x48767F: PyString_Repr (in /usr/bin/python2.7)
==4325==    by 0x47CA60: PyObject_Repr (in /usr/bin/python2.7)
==4325==    by 0x46942D: PyInt_FromString (in /usr/bin/python2.7)
==4325==    by 0x45F3DE: PyNumber_Int (in /usr/bin/python2.7)
==4325==    by 0x46959B: ??? (in /usr/bin/python2.7)
==4325==    by 0x48BEB2: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4996BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x668e020 is 336 bytes inside a block of size 1,104 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4C247B: ??? (in /usr/bin/python2.7)
==4325==    by 0x499060: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47EC1B: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x487F91: PyString_FromFormatV (in /usr/bin/python2.7)
==4325==    by 0x4A183B: PyErr_Format (in /usr/bin/python2.7)
==4325==    by 0x46946D: PyInt_FromString (in /usr/bin/python2.7)
==4325==    by 0x45F3DE: PyNumber_Int (in /usr/bin/python2.7)
==4325==    by 0x46959B: ??? (in /usr/bin/python2.7)
==4325==    by 0x48BEB2: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4996BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x668e020 is 336 bytes inside a block of size 1,104 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4C247B: ??? (in /usr/bin/python2.7)
==4325==    by 0x499060: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x46948E: PyInt_FromString (in /usr/bin/python2.7)
==4325==    by 0x45F3DE: PyNumber_Int (in /usr/bin/python2.7)
==4325==    by 0x46959B: ??? (in /usr/bin/python2.7)
==4325==    by 0x48BEB2: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4996BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x668e020 is 336 bytes inside a block of size 1,104 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4C247B: ??? (in /usr/bin/python2.7)
==4325==    by 0x499060: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4632C8: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BE67: PyDict_SetItemString (in /usr/bin/python2.7)
==4325==    by 0x49CB45: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x668e020 is 336 bytes inside a block of size 1,104 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4C247B: ??? (in /usr/bin/python2.7)
==4325==    by 0x499060: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x49A4B7: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x66e5020 is 656 bytes inside a block of size 1,104 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4C247B: ??? (in /usr/bin/python2.7)
==4325==    by 0x499060: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x46AFB4: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C62E2: ??? (in /usr/bin/python2.7)
==4325==    by 0x49FD7A: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x667d020 is 2,976 bytes inside a block of size 3,696 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x464D27: ??? (in /usr/bin/python2.7)
==4325==    by 0x499060: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Conditional jump or move depends on uninitialised value(s)
==4325==    at 0x47EA08: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x52321A: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==4325==    by 0x523896: PyParser_New (in /usr/bin/python2.7)
==4325==    by 0x45B2E2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Use of uninitialised value of size 8
==4325==    at 0x47EA22: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x52321A: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==4325==    by 0x523896: PyParser_New (in /usr/bin/python2.7)
==4325==    by 0x45B2E2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x52321A: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==4325==    by 0x523896: PyParser_New (in /usr/bin/python2.7)
==4325==    by 0x45B2E2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x6ab3020 is 432 bytes inside a block of size 676 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x52321A: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==4325==    by 0x523896: PyParser_New (in /usr/bin/python2.7)
==4325==    by 0x45B2E2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Conditional jump or move depends on uninitialised value(s)
==4325==    at 0x47EC24: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Use of uninitialised value of size 8
==4325==    at 0x47EC3E: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2FB9: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C2F58: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C2F58: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C2F58: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FF8DC: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==  Address 0x6b11020 is 32,912 bytes inside a block of size 36,032 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x45B441: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2D11: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FF8DC: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x6b11020 is 32,912 bytes inside a block of size 36,032 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x45B441: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2DCF: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FF8DC: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x6b12020 is 144 bytes inside a block of size 320 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4EEDC8: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FA965: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFA34: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x6b15020 is 144 bytes inside a block of size 384 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4EEDC8: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FA965: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFA34: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF812: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFA34: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==  Address 0x6b16020 is 448 bytes inside a block of size 832 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4AAEA7: PyCode_Optimize (in /usr/bin/python2.7)
==4325==    by 0x4F1BD9: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FA955: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFA34: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C61B2: ??? (in /usr/bin/python2.7)
==4325==    by 0x49FD7A: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x4EEB91: PyEval_EvalCode (in /usr/bin/python2.7)
==4325==    by 0x4FD51E: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==4325==  Address 0x6aaf020 is 5,968 bytes inside a block of size 8,192 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x464302: ??? (in /usr/bin/python2.7)
==4325==    by 0x4D0371: ??? (in /usr/bin/python2.7)
==4325==    by 0x4D03CF: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C579C: ??? (in /usr/bin/python2.7)
==4325==    by 0x49910B: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47EC1B: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x4EF62C: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F3B16: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F3006: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F385E: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F3969: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F3037: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F729C: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAAF5: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFA34: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==  Address 0x6b4e020 is not stack'd, malloc'd or (recently) free'd
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4FA965: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFA34: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==  Address 0x6b4e020 is not stack'd, malloc'd or (recently) free'd
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x42B5C6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A68A3: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6E7A: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4FB164: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A0AB1: _PyCodec_Lookup (in /usr/bin/python2.7)
==4325==    by 0x4A0B1B: ??? (in /usr/bin/python2.7)
==4325==    by 0x42E337: Py_InitializeEx (in /usr/bin/python2.7)
==4325==  Address 0x6b6d020 is 16 bytes inside a block of size 128 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A7531: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x42B5C6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47EC1B: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFAFA: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bef020 is 240 bytes inside a block of size 480 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFAFA: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2DA0: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FFB2F: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bf0020 is 816 bytes inside a block of size 960 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFAFA: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2DCF: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C2F58: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C2F58: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FFB2F: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bf0020 is 816 bytes inside a block of size 960 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFAFA: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Conditional jump or move depends on uninitialised value(s)
==4325==    at 0x47EA08: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2DA0: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FFB2F: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Use of uninitialised value of size 8
==4325==    at 0x47EA22: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2DA0: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FFB2F: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Conditional jump or move depends on uninitialised value(s)
==4325==    at 0x47EA08: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2D71: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FFB2F: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Use of uninitialised value of size 8
==4325==    at 0x47EA22: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2D71: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FFB2F: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C2CD9: ??? (in /usr/bin/python2.7)
==4325==    by 0x5236ED: PyNode_Free (in /usr/bin/python2.7)
==4325==    by 0x4FFB2F: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bf0020 is 816 bytes inside a block of size 960 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FFAFA: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47EC1B: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x4EF62C: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F2004: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F3037: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F729C: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAAF5: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bf7020 is 224 bytes inside a block of size 768 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x4EF62C: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F9E8D: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAAF5: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47EC1B: PyObject_Realloc (in /usr/bin/python2.7)
==4325==    by 0x4EF62C: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F9A58: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAAF5: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bf7020 is 224 bytes inside a block of size 768 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x4EF62C: ??? (in /usr/bin/python2.7)
==4325==    by 0x4F9E8D: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAAF5: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x49B78A: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x4EEB91: PyEval_EvalCode (in /usr/bin/python2.7)
==4325==    by 0x4FF7F3: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6c0e020 is 240 bytes inside a block of size 448 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x752E9AC: PrintCircular (window.c:345)
==4325==    by 0x750D11E: PrintHWState (holtwinters.c:61)
==4325==    by 0x74FD23A: anomaly_holtwinters (anomalymodule.c:306)
==4325==    by 0x499060: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x4EEB91: PyEval_EvalCode (in /usr/bin/python2.7)
==4325==    by 0x4FF7F3: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)] [('1', 15), ('2', 14), ('3', 3), ('4', 4), ('5', 1)]
(1.0, 1.0)
(0.0, 0.0)
HW SHW  B 0
alpha 5.000000e-01 beta 5.000000e-01 gamma 5.000000e-01
yt [ C 0 D 1 X 0,  (2.996155e+01 ) ] at [ C 0 D 1 X 0,  (2.819285e+01 ) ] bt [ C 0 D 1 X 0,  (9.993827e-01 ) ] dt [ C 0 D 1 X 0,  (6.736887e-02 ) ]
C storage 10 :
   C B 0 top 0 length 10 D 1
   Array: [ C 0 D 1 X 20,  (7.633523e-01 ) ][ C 0 D 1 X 21,  (7.693138e-01 ) ][ C 0 D 1 X 22,  (7.824689e-01 ) ][ C 0 D 1 X 23,  (8.028699e-01 ) ][ C 0 D 1 X 24,  (8.273457e-01 ) ][ C 0 D 1 X 25,  (8.516385e-01 ) ][ C 0 D 1 X 26,  (8.720314e-01 ) ][ C 0 D 1 X 27,  (8.862542e-01 ) ][ C 0 D 1 X 28,  (8.937127e-01 ) ][ C 0 D 1 X 29,  (8.952219e-01 ) ]
D storage 10 :
   C B 0 top 0 length 10 D 1
   Array: [ C 0 D 1 X 0,  (1.202210e-01 ) ][ C 0 D 1 X 0,  (3.306819e-01 ) ][ C 0 D 1 X 0,  (3.451494e-01 ) ][ C 0 D 1 X 0,  (2.486621e-01 ) ][ C 0 D 1 X 0,  (1.518742e-01 ) ][ C 0 D 1 X 0,  (1.066116e-01 ) ][ C 0 D 1 X 0,  (8.848206e-02 ) ][ C 0 D 1 X 0,  (9.652490e-02 ) ][ C 0 D 1 X 0,  (9.160942e-02 ) ][ C 0 D 1 X 0,  (6.736887e-02 ) ]

HW [(0L, 1.0, nan, 0.0, 0.0), (1L, 1.0, 1.0, 0.0, 0.0), (2L, 1.0, 1.0, 0.75, 0.0), (3L, 1.0, 1.0, 1.9375, 0.0), (4L, 1.0, 1.0, 3.296875, 0.0), (5L, 1.0, 1.0, 4.65234375, 0.0), (6L, 1.0, 1.0, 5.9169921875, 0.0), (7L, 1.0, 1.0, 7.070068359375, 0.0), (8L, 1.0, 1.0, 8.12908935546875, 0.0), (9L, 1.0, 1.0, 9.126327514648438, 0.0), (10L, 1.0, 1.0, 10.343364715576172, 0.0), (11L, 0.0, 0.0, 11.491042137145996, 0.5), (12L, 0.0, 0.0, 12.37962031364441, 0.625), (13L, 0.0, 0.0, 13.150879323482513, 0.53125), (14L, 0.0, 0.0, 13.932382747530937, 0.3515625), (15L, 1.0, 0.1475107902523296, 14.796093460172415, 0.173828125), (16L, 1.0, 0.829063498885275, 15.75719693582505, 0.04150390625), (17L, 1.0, 0.830538717007091, 16.793261451413855, 0.0350341796875), (18L, 1.0, 0.5133932521558959, 17.86735761881573, 0.064544677734375), (19L, 0.0, 0.0, 18.945634382529533, 0.06316375732421875), (20L, 0.0, 0.0, 20.06875963841958, 0.17168235778808594), (21L, 0.0, 0.0, 21.165842651483217, 0.49552106857299805), (22L, 0.0, 0.0, 22.187988628715857, 0.5023101568222046), (23L, 0.0, 0.0, 23.156259479755988, 0.3410646617412567), (24L, 0.0, 0.0, 24.094158430554714, 0.2095898762345314), (25L, 0.0, 0.0, 25.024355891911082, 0.1888673324137926), (26L, 0.0, 0.0, 25.965189361966026, 0.14215348521247506), (27L, 0.0, 0.0, 26.927836567920743, 0.12088636413682252), (28L, 0.0, 0.0, 27.915374687746514, 0.09859352945932187), (29L, 1.0, 0.22650616355861874, 28.924026948077955, 0.05876468739734264)]
HWA SHW  B 0
alpha 5.000000e-01 beta 5.000000e-01 gamma 5.000000e-01
yt [ C 0 D 1 X 0,  (2.996155e+01 ) ] at [ C 0 D 1 X 0,  (2.819285e+01 ) ] bt [ C 0 D 1 X 0,  (9.993827e-01 ) ] dt [ C 0 D 1 X 0,  (6.736887e-02 ) ]
C storage 10 :
   C B 0 top 0 length 10 D 1
   Array: [ C 0 D 1 X 20,  (7.633523e-01 ) ][ C 0 D 1 X 21,  (7.693138e-01 ) ][ C 0 D 1 X 22,  (7.824689e-01 ) ][ C 0 D 1 X 23,  (8.028699e-01 ) ][ C 0 D 1 X 24,  (8.273457e-01 ) ][ C 0 D 1 X 25,  (8.516385e-01 ) ][ C 0 D 1 X 26,  (8.720314e-01 ) ][ C 0 D 1 X 27,  (8.862542e-01 ) ][ C 0 D 1 X 28,  (8.937127e-01 ) ][ C 0 D 1 X 29,  (8.952219e-01 ) ]
D storage 10 :
   C B 0 top 0 length 10 D 1
   Array: [ C 0 D 1 X 0,  (1.202210e-01 ) ][ C 0 D 1 X 0,  (3.306819e-01 ) ][ C 0 D 1 X 0,  (3.451494e-01 ) ][ C 0 D 1 X 0,  (2.486621e-01 ) ][ C 0 D 1 X 0,  (1.518742e-01 ) ][ C 0 D 1 X 0,  (1.066116e-01 ) ][ C 0 D 1 X 0,  (8.848206e-02 ) ][ C 0 D 1 X 0,  (9.652490e-02 ) ][ C 0 D 1 X 0,  (9.160942e-02 ) ][ C 0 D 1 X 0,  (6.736887e-02 ) ]

HWA [(0L, 1.0, nan, 0.0, 0.0), (1L, 1.0, 1.0, 0.0, 0.0), (2L, 1.0, 1.0, 0.75, 0.0), (3L, 1.0, 1.0, 1.9375, 0.0), (4L, 1.0, 1.0, 3.296875, 0.0), (5L, 1.0, 1.0, 4.65234375, 0.0), (6L, 1.0, 1.0, 5.9169921875, 0.0), (7L, 1.0, 1.0, 7.070068359375, 0.0), (8L, 1.0, 1.0, 8.12908935546875, 0.0), (9L, 1.0, 1.0, 9.126327514648438, 0.0), (10L, 1.0, 1.0, 10.343364715576172, 0.0), (11L, 0.0, 0.0, 11.491042137145996, 0.5), (12L, 0.0, 0.0, 12.37962031364441, 0.625), (13L, 0.0, 0.0, 13.150879323482513, 0.53125), (14L, 0.0==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525476: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF812: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bfd020 is 608 bytes inside a block of size 1,964 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4AAEA7: PyCode_Optimize (in /usr/bin/python2.7)
==4325==    by 0x4F1BD9: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FA955: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF812: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bfd020 is 608 bytes inside a block of size 1,964 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4AAEA7: PyCode_Optimize (in /usr/bin/python2.7)
==4325==    by 0x4F1BD9: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FA955: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF812: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bfd020 is 608 bytes inside a block of size 1,964 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4AAEA7: PyCode_Optimize (in /usr/bin/python2.7)
==4325==    by 0x4F1BD9: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FA955: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FAD6C: PyAST_Compile (in /usr/bin/python2.7)
==4325==    by 0x4FF7DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x42CDCF: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325==    by 0x418DB4: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6b6c020 is 2,688 bytes inside a block of size 4,370 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4FE5FC: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x42B5C6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A68A3: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6E7A: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4FB164: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A0AB1: _PyCodec_Lookup (in /usr/bin/python2.7)
==4325==    by 0x4A0B1B: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C77AF: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6b6c020 is 2,688 bytes inside a block of size 4,370 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4FE5FC: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x42B5C6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A68A3: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6E7A: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4FB164: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A0AB1: _PyCodec_Lookup (in /usr/bin/python2.7)
==4325==    by 0x4A0B1B: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6b6c020 is 2,688 bytes inside a block of size 4,370 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4FE5FC: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x42B5C6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A68A3: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6E7A: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4FB164: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A0AB1: _PyCodec_Lookup (in /usr/bin/python2.7)
==4325==    by 0x4A0B1B: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525476: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6391020 is 1,440 bytes inside a block of size 1,608 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A7531: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6391020 is 1,440 bytes inside a block of size 1,608 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A7531: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6b55020 is not stack'd, malloc'd or (recently) free'd
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A7C8: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x668e020 is 336 bytes inside a block of size 1,104 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4C247B: ??? (in /usr/bin/python2.7)
==4325==    by 0x499060: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x525499: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6526020 is 1,280 bytes inside a block of size 1,864 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74C7: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x5254BD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6526020 is 1,280 bytes inside a block of size 1,864 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74C7: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB212: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6b7c020 is 496 bytes inside a block of size 1,008 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4C77AF: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB212: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6b7c020 is 496 bytes inside a block of size 1,008 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Conditional jump or move depends on uninitialised value(s)
==4325==    at 0x47EA08: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Use of uninitialised value of size 8
==4325==    at 0x47EA22: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525579: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x653a020 is 416 bytes inside a block of size 456 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x5254BD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x5254E1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6548020 is 608 bytes inside a block of size 1,608 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74DD: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB212: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6664020 is 3,056 bytes inside a block of size 3,072 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x47A597: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A7C8: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525476: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB212: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6544020 is 640 bytes inside a block of size 751 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x525476: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4D6365: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD104: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x63c7020 is 1,200 bytes inside a block of size 1,384 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x46AEDC: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE568: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB212: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB1F4: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB1F4: ??? (in /usr/bin/python2.7)
==4325==    by 0x46255E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD104: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==  Address 0x6417020 is 272 bytes inside a block of size 440 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x525587: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD779: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C77DF: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB212: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB1F4: ??? (in /usr/bin/python2.7)
==4325==    by 0x46255E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD104: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==  Address 0x640b020 is 1,568 bytes inside a block of size 3,072 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x47A597: ??? (in /usr/bin/python2.7)
==4325==    by 0x4D6365: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD104: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB212: ??? (in /usr/bin/python2.7)
==4325==    by 0x46255E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD104: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6509020 is 0 bytes inside a block of size 8 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4E0888: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x4E0A8D: ??? (in /usr/bin/python2.7)
==4325==    by 0x4DE875: PyType_Ready (in /usr/bin/python2.7)
==4325==    by 0x48E837: ??? (in /usr/bin/python2.7)
==4325==    by 0x48C23A: ??? (in /usr/bin/python2.7)
==4325==    by 0x499060: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x4C7435: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x462538: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD104: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x650a020 is 256 bytes inside a block of size 768 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x47A597: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB212: ??? (in /usr/bin/python2.7)
==4325==    by 0x46255E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD104: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x48CE51: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47C00C: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FCE91: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6664020 is 3,056 bytes inside a block of size 3,072 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x47A597: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A7C8: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x47BFA3: _PyModule_Clear (in /usr/bin/python2.7)
==4325==    by 0x4FD022: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FCECE: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x62d8020 is not stack'd, malloc'd or (recently) free'd
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FCEF6: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x62d8020 is not stack'd, malloc'd or (recently) free'd
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A50D: ??? (in /usr/bin/python2.7)
==4325==    by 0x42ADE0: _PyImport_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DC4C: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6302020 is 8 bytes after a block of size 8 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4E0888: ??? (in /usr/bin/python2.7)
==4325==    by 0x4E09E3: ??? (in /usr/bin/python2.7)
==4325==    by 0x4DE875: PyType_Ready (in /usr/bin/python2.7)
==4325==    by 0x42B78D: _PyImportHooks_Init (in /usr/bin/python2.7)
==4325==    by 0x42E222: Py_InitializeEx (in /usr/bin/python2.7)
==4325==    by 0x41891B: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A50D: ??? (in /usr/bin/python2.7)
==4325==    by 0x42ADE0: _PyImport_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DC4C: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6303020 is 560 bytes inside a block of size 628 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A50D: ??? (in /usr/bin/python2.7)
==4325==    by 0x42ADE0: _PyImport_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DC4C: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A50D: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A50D: ??? (in /usr/bin/python2.7)
==4325==    by 0x42ADE0: _PyImport_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DC4C: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x63a0020 is 208 bytes inside a block of size 280 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4D6365: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x4FD116: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Conditional jump or move depends on uninitialised value(s)
==4325==    at 0x47EA08: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A50D: ??? (in /usr/bin/python2.7)
==4325==    by 0x42ADE0: _PyImport_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DC4C: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Use of uninitialised value of size 8
==4325==    at 0x47EA22: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A50D: ??? (in /usr/bin/python2.7)
==4325==    by 0x42ADE0: _PyImport_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DC4C: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
, 0.0, 13.932382747530937, 0.3515625), (15L, 1.0, 0.1475107902523296, 14.796093460172415, 0.173828125), (16L, 1.0, 0.829063498885275, 15.75719693582505, 0.04150390625), (17L, 1.0, 0.830538717007091, 16.793261451413855, 0.0350341796875), (18L, 1.0, 0.5133932521558959, 17.86735761881573, 0.064544677734375), (19L, 0.0, 0.0, 18.945634382529533, 0.06316375732421875), (20L, 0.0, 0.0, 20.06875963841958, 0.17168235778808594), (21L, 0.0, 0.0, 21.165842651483217, 0.49552106857299805), (22L, 0.0, 0.0, 22.187988628715857, 0.5023101568222046), (23L, 0.0, 0.0, 23.156259479755988, 0.3410646617412567), (24L, 0.0, 0.0, 24.094158430554714, 0.2095898762345314), (25L, 0.0, 0.0, 25.024355891911082, 0.1888673324137926), (26L, 0.0, 0.0, 25.965189361966026, 0.14215348521247506), (27L, 0.0, 0.0, 26.927836567920743, 0.12088636413682252), (28L, 0.0, 0.0, 27.915374687746514, 0.09859352945932187), (29L, 1.0, 0.22650616355861874, 28.924026948077955, 0.05876468739734264)]
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x489B39: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A50D: ??? (in /usr/bin/python2.7)
==4325==    by 0x42ADE0: _PyImport_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DC4C: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x62eb020 is 16 bytes inside a block of size 128 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x42F821: _PySys_Init (in /usr/bin/python2.7)
==4325==    by 0x42E192: Py_InitializeEx (in /usr/bin/python2.7)
==4325==    by 0x41891B: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x42ADE0: _PyImport_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DC4C: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x62ee020 is not stack'd, malloc'd or (recently) free'd
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF2A4: PyThreadState_Clear (in /usr/bin/python2.7)
==4325==    by 0x42C1ED: PyInterpreterState_Clear (in /usr/bin/python2.7)
==4325==    by 0x42DC54: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6bf4020 is 672 bytes inside a block of size 848 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4ABE80: PyArena_AddPyObject (in /usr/bin/python2.7)
==4325==    by 0x536616: ??? (in /usr/bin/python2.7)
==4325==    by 0x53489B: ??? (in /usr/bin/python2.7)
==4325==    by 0x5362D5: ??? (in /usr/bin/python2.7)
==4325==    by 0x534D59: ??? (in /usr/bin/python2.7)
==4325==    by 0x539094: ??? (in /usr/bin/python2.7)
==4325==    by 0x53A30C: PyAST_FromNode (in /usr/bin/python2.7)
==4325==    by 0x4FFB24: PyParser_ASTFromFile (in /usr/bin/python2.7)
==4325==    by 0x42CD93: PyRun_FileExFlags (in /usr/bin/python2.7)
==4325==    by 0x42D797: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x525476: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C777F: ??? (in /usr/bin/python2.7)
==4325==    by 0x46AFB4: ??? (in /usr/bin/python2.7)
==4325==    by 0x42C228: PyInterpreterState_Clear (in /usr/bin/python2.7)
==4325==    by 0x42DC54: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6b6d020 is 16 bytes inside a block of size 128 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x46E3B2: PyList_Append (in /usr/bin/python2.7)
==4325==    by 0x4A72E6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A7531: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A73ED: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A74B1: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FE545: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==4325==    by 0x4FE5F1: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x42B5C6: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4C77DF: ??? (in /usr/bin/python2.7)
==4325==    by 0x46AFB4: ??? (in /usr/bin/python2.7)
==4325==    by 0x42C228: PyInterpreterState_Clear (in /usr/bin/python2.7)
==4325==    by 0x42DC54: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6b12020 is 144 bytes inside a block of size 320 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB212: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB1F4: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x4CB1F4: ??? (in /usr/bin/python2.7)
==4325==    by 0x489B3D: ??? (in /usr/bin/python2.7)
==4325==    by 0x48D0AC: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A5CB: ??? (in /usr/bin/python2.7)
==4325==    by 0x42C24E: PyInterpreterState_Clear (in /usr/bin/python2.7)
==4325==    by 0x42DC54: Py_Finalize (in /usr/bin/python2.7)
==4325==  Address 0x6b78020 is 35,904 bytes inside a block of size 36,414 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x4FE5FC: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==4325==    by 0x4FC670: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FD707: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A626F: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A68A3: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325==    by 0x4987C5: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==4325==    by 0x49B3BD: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x42C24E: PyInterpreterState_Clear (in /usr/bin/python2.7)
==4325==    by 0x42DC54: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6387020 is 288 bytes inside a block of size 768 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x479722: ??? (in /usr/bin/python2.7)
==4325==    by 0x47BE67: PyDict_SetItemString (in /usr/bin/python2.7)
==4325==    by 0x4FD35F: PyImport_AddModule (in /usr/bin/python2.7)
==4325==    by 0x4FD480: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==4325==    by 0x4FD759: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A5ED2: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6149: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6A66: ??? (in /usr/bin/python2.7)
==4325==    by 0x4A6F45: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==4325==    by 0x4980D6: ??? (in /usr/bin/python2.7)
==4325==    by 0x45FED3: PyObject_Call (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x42C275: PyInterpreterState_Clear (in /usr/bin/python2.7)
==4325==    by 0x42DC54: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6b12020 is 144 bytes inside a block of size 320 free'd
==4325==    at 0x4C290A4: realloc (vg_replace_malloc.c:525)
==4325==    by 0x4C3213: PyNode_AddChild (in /usr/bin/python2.7)
==4325==    by 0x4C3613: PyParser_AddToken (in /usr/bin/python2.7)
==4325==    by 0x45B361: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4D50AD: PyDict_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DCA4: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x63a0020 is 208 bytes inside a block of size 280 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x47A5AE: ??? (in /usr/bin/python2.7)
==4325==    by 0x4D6365: ??? (in /usr/bin/python2.7)
==4325==    by 0x47A86E: ??? (in /usr/bin/python2.7)
==4325==    by 0x47B1A5: PyDict_SetItem (in /usr/bin/python2.7)
==4325==    by 0x4FD116: PyImport_Cleanup (in /usr/bin/python2.7)
==4325==    by 0x42DC47: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Conditional jump or move depends on uninitialised value(s)
==4325==    at 0x47EA08: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4D50AD: PyDict_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DCA4: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Use of uninitialised value of size 8
==4325==    at 0x47EA22: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x4D50AD: PyDict_Fini (in /usr/bin/python2.7)
==4325==    by 0x42DCA4: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325== 
==4325== Invalid read of size 4
==4325==    at 0x47E9FF: PyObject_Free (in /usr/bin/python2.7)
==4325==    by 0x523674: PyGrammar_RemoveAccelerators (in /usr/bin/python2.7)
==4325==    by 0x42DCB3: Py_Finalize (in /usr/bin/python2.7)
==4325==    by 0x418E48: Py_Main (in /usr/bin/python2.7)
==4325==    by 0x5EF1EFE: (below main) (libc-start.c:226)
==4325==  Address 0x6ab2020 is 368 bytes inside a block of size 992 free'd
==4325==    at 0x4C282ED: free (vg_replace_malloc.c:366)
==4325==    by 0x45B460: ??? (in /usr/bin/python2.7)
==4325==    by 0x4FF90D: PyParser_ASTFromString (in /usr/bin/python2.7)
==4325==    by 0x4FFA16: PyRun_StringFlags (in /usr/bin/python2.7)
==4325==    by 0x49D930: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325==    by 0x499501: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49982E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==4325==    by 0x49FD54: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==4325== 
==4325== 
==4325== HEAP SUMMARY:
==4325==     in use at exit: 1,539,561 bytes in 460 blocks
==4325==   total heap usage: 7,942 allocs, 7,482 frees, 9,644,614 bytes allocated
==4325== 
==4325== LEAK SUMMARY:
==4325==    definitely lost: 2,048 bytes in 2 blocks
==4325==    indirectly lost: 0 bytes in 0 blocks
==4325==      possibly lost: 210,800 bytes in 40 blocks
==4325==    still reachable: 1,326,713 bytes in 418 blocks
==4325==         suppressed: 0 bytes in 0 blocks
==4325== Rerun with --leak-check=full to see details of leaked memory
==4325== 
==4325== For counts of detected and suppressed errors, rerun with: -v
==4325== Use --track-origins=yes to see where uninitialised values come from
==4325== ERROR SUMMARY: 911 errors from 91 contexts (suppressed: 6 from 6)
